server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: order-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: true

        enable.idempotence: true

      acks: all
      retries: 10

logging:
  level:
    root: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.springframework.transaction: WARN
    org.hibernate.SQL: WARN
    com.example: INFO